murgatt/recode-converter

src/store/file/file.utils.js

Related issue #21 
In destination input, default destination is not displayed on Windows because of the path separator.
Check if the platform is windows and set the path separator accordingly: `\`
Run the app on Windows and add a file, the default destination should be displayed

fix(windows): default destination is not displayed on Windows

---

src/components/File/File.js
src/components/FileList/FileList.js
src/components/FileStreams/FileStreams.js
src/components/FileStreams/index.js
src/i18n/en.json
src/i18n/fr.json

Add a collapse panel in each file card to display streams info

feat(files): add file streams info in a collapse panel

---

public/ffmpeg.js
src/components/FileStreams/FileStreams.js
src/components/StreamMetadataInput/StreamMetadataInput.js
src/components/StreamMetadataInput/index.js
src/i18n/fr.json
src/store/file/file.actions.js
src/store/file/file.utils.js

Launch the app, add a file to convert and display streams table.
Edit stream title inputs.
New titles should be visible in the output file.

feat(conversion): add & edit stream title

---

src/components/FileStreams/FileStreams.js
src/components/StreamMetadataInput/StreamMetadataInput.js

- Add "disabled" style on stream row when the stream is ignored
- Disabled metadata input when stream is ignored or when the conversion has started

feat: improve file streams edit UI

---

src/store/file/file.actions.js

Metadata added on an ignored stream is added to the next stream in the output file.
I added a `removeStreamMetadata` action to remove all metadata related to a stream when it's ignored.
Start the app, add a file and add/change a stream title in the file streams table then unchecked a stream to ignore it. It should reset the title to the initial title and metadata should not be present in the output file after running the conversion

fix(conversion): metadata on ignored stream

---

docs/index.html
docs/index.js
package.json
public/electron.js
yarn.lock

On Mac, once the app is packaged, ffmpeg & ffprobe are not found and can't be used (and any other command in the PATH).
Using [fix-path](https://github.com/sindresorhus/fix-path) solved this issue.
https://github.com/electron/electron/issues/7688
https://stackoverflow.com/questions/48420819/cannot-execute-shell-command-from-electron-packaged-app
Package the app and try to run it, display file streams info & run a conversion

fix: app crash on mac when using ffmpeg or ffprobe

---

src/store/conversion/conversion.actions.js
src/store/conversion/conversion.reducer.js
src/store/conversion/conversion.selectors.js
src/store/file/file.actions.js
src/store/file/file.selectors.js

Related issue #45 
If a file was added during a conversion, at the end of the conversion, the status is still `converting`.
What was done:
- add a dynamic conversion list at the start of the conversion
- remove file from conversion list when this has been converted
- improve the conversion progress check based  on the conversion list
- run the app & add a file to convert
- start the conversion and add a file before the end
- at the end of the conversion it should really and the start/pause button should be "start"

fix(conversion): wrong status if file added during conversion

---

package.json

I moved the dependencies related to testing-library to dev dependencies.
This is the right thing to do according the documentation : 
https://testing-library.com/docs/react-testing-library/intro
The application should still bundle after a clean install and the tests should also pass.

build(dependencies): move testing library to dev dependencies

---

.github/pull_request_template.md
src/store/conversion/conversion.actions.js

Fixes #63 
When multiple files are added from different directories and the destination is not manually set a conversion error occurred due to wrong destination.
In this case the destination is set to "Same as source" and passed in the conversion options.
In this case, we now pass an empty destination, this way the destination is automatically set as the converted file directory during the conversion.
Add at least two files from different directory
Do not set a destination
Start the conversion

fix: conversion error when destination is 'Same as source'

---

public/conversionManager.js
public/ffmpeg.js
src/registerElectronEvents.js

When a conversion error occurred there is no way to see the details of what happened.
This PR add a console error on the front side to display the server side error.
Do something wrong to trigger an error during conversion
Start the conversion and open the development console to see the error

feat: add front side console error when conversion fails

---

.eslintignore
.github/workflows/main.yml
electron/electron-env.d.ts
electron/main.ts
package.json
tsconfig.json
tsconfig.node.json

- remove `composite` property from `tsconfig.node.json` (fix locales json import)
- change `references` to `extends` in `tsconfig.json`
- add `types` script in `package.json` and `Types` job to check type errors in CI
- temp ignored files in `.eslintignore` are no longer useful
- `DIST` & `VITE_PUBLIC` are now constants instead of env variables

fix(v2): typescript errors when importing shared files

---

electron/ConversionManager.ts
electron/conversion-events.types.ts
electron/convert/convert.ts
electron/electron-env.d.ts
electron/preload.ts
src/components/ConversionSettingsForm/BitrateSelect.tsx
src/components/ConversionSettingsForm/ChannelsSelect.tsx
src/components/ConversionSettingsForm/CodecSelect.tsx
src/components/ConversionSettingsForm/ConversionSettingsForm.tsx
src/components/ConversionSettingsForm/SampleRateSelect.tsx
src/components/FileCard/FileCard.tsx
src/components/FileCard/__tests__/FileCard.test.tsx
src/components/FileImport.tsx
src/components/FileList.tsx
src/components/Footer/DestinationInput.tsx
src/components/Footer/Footer.tsx
src/components/Footer/__tests__/DestinationInput.test.tsx
src/components/StreamTable/StreamTable.tsx
src/components/StreamTable/StreamTableRow.tsx
src/components/StreamTable/__tests__/StreamTableRow.test.tsx
src/components/__tests__/FileImport.test.tsx
src/components/__tests__/FileList.test.tsx
src/components/ui/Tooltip.tsx
src/hooks/useConversionEvents.ts
src/i18n/locales/en.json
src/i18n/locales/fr.json
src/routes/Converter.tsx
src/store/selectors.ts
src/store/store.types.ts
src/store/useStore.ts

- send `conversion-end` event when all files have been converted
- add a tooltip on "Stop conversion" button
- new `isConversionRunning` state in store to know if the conversion is running
- conversion settings form is now disabled when the conversion is running
- file stream can only be editted when file is `imported`
- a file cannot be removed when the conversion or if the file is still being converted
- files cannot be added to file list when the conversion is running
- file list cannot be cleared when the conversion is running or if a file is still being converted
- destination input is disabled when the conversion is running

feat(v2): disable states during conversion

---

src/components/ConversionSettingsForm/ConversionSettingsForm.tsx
src/i18n/locales/en.json
src/i18n/locales/fr.json
src/store/selectors.ts
src/store/store.types.ts
src/store/useStore.ts

- save current form state inside store on form change
- set default form values from store
- remove `useEffect` to reset values when codec changes and use a dedicated handler instead

feat(v2): persist form data

---

electron/ConversionManager.ts
electron/conversion-events.types.ts
package.json
pnpm-lock.yaml
schema/file.types.ts
src/components/FileCard/FileCard.tsx
src/components/FileCard/__tests__/FileCard.test.tsx
src/components/SettingsForm/FfmpegCommandSwitch.tsx
src/components/SettingsForm/LanguageSelect.tsx
src/components/SettingsForm/NotificationsSelect.tsx
src/components/SettingsForm/SettingsForm.tsx
src/components/SettingsForm/ThemeSelect.tsx
src/components/ui/Checkbox.tsx
src/components/ui/Input.tsx
src/components/ui/Switch.tsx
src/hooks/useConversionEvents.ts
src/i18n/locales/en.json
src/i18n/locales/fr.json
src/schema/settings.schema.ts
src/store/store.types.ts
src/store/useStore.ts
src/utils/__tests__/settings.utils.test.ts
src/utils/settings.utils.ts
tailwind.config.js

- display spawned ffmpeg command after conversion start if related setting is set to true
- send ffmpeg command from main to renderer in `fileConversionStart` callback and set it in according file object in store
- add `ffmpegCommand` boolean setting (default to false) in settings form, it's displayed as a switch
- add UI component: Switch
- fix settings label by using `FormItem` to wrap form selects + increase label width in settings form
- `getSettingsFromStorage` now returns settings in local storage with default settings to avoid missing setting if a single setting is not defined in local storage

feat(v2): display ffmpeg command

---

.github/workflows/build.yml
.github/workflows/release-please.yml
CHANGELOG.md
electron-builder.json5
package.json

- update build action:
- run when a release is published
- setup, install dependencies & run build manually with `pnpm run build` script
- publish app automatically by uploading artifacts to latest release with [electron builder](https://www.electron.build/configuration/publish.html)
- add [release-please-action](https://github.com/google-github-actions/release-please-action) to create release PR, update changelog & create release automatically
- add back CHANGELOG.md (from main) and remove standard version description
- set version to `1.2.0` (will bump later automatically to `2.0.0` with release-please)

ci(v2): release flow

---

electron/convert/convert.ts
electron/convert/convert.utils.ts
src/components/StreamTable/StreamTablePropertiesCell.tsx

- fix title metadata with spaces causing error in output command generated by fluent-ffmpeg
- fix bitrate displayed as `NaN` in stream properties when there is no bitrate (value is `N/A`)
- fix wrong stream index when setting a stream title and at least one stream (before in the stream list) has been ignored

fix(v2): minor fixes

---

src/components/AppMenu/AppMenu.tsx
src/components/ExternalLink.tsx
src/components/UpdateAvailableModal.tsx
src/constants.ts
src/i18n/locales/en.json
src/i18n/locales/fr.json
src/router.tsx
src/routes/About.tsx

- add about page with app version and link to github user, github repo & website
- add `ExternalLink` component to open link in default browser with electron API
- externalise some constants in a global `constants.ts` (`APP_WEBSITE_URL`, `AUTHOR_GITHUB_URL`, `GITHUB_REPOSITORY_URL`)

feat(v2): add about page

---

package.json
pnpm-lock.yaml

- bump `vite` from `4.5.0` to `5.0.12`
- bump `vite-plugin-electron` from `0.14.1` to `0.28.0`
- bump vitest from `0.34.6` to `1.2.2`

chore(deps): bump vite, vite-plugin-electron & vitest

---

src/test/vitest-setup.ts
src/utils/file.utils.ts

On Windows, when a file is added, we should see the directory has default destination path in destination input. Instead we only see "Destination" placeholder.
This is because on Windows path separator is `\\` instead of `/`.
When checking if all files are from same directory, we now check the platform and change path separator if Windows.
- On Windows, open app and add one file (or multiple files from same directory)
- We should see the directory as destination path

fix(v2): fix default destination path on Windows

---

.github/workflows/build.yml
.github/workflows/main.yml
README.md
pnpm-lock.yaml

[pnpm v9](https://github.com/pnpm/pnpm/releases/tag/v9.0.0) introduced new lockfile format v9
Convert lockfile from v6 to v9 by upgrading to pnpm `9.4.0` and running `pnpm i`
The version of pnpm is also updated in github actions and README.md

chore: convert lockfile to v9

---

electron-builder.json5

**Context**
Once downloaded and installed on a Mac, the app cannot be opened since `2.0.4`.
The target architecture was not specified and it automatically switched from `universal` to `arm64` changing how the Gatekeeper is warning about unsigned app and blocking it completely.
**Fix**
Set `universal` as target architecture for Mac build
Build app, download and install it. It's now possible to open by right clicking on it.

fix: Mac app cannot be opened

---

electron/electron-env.d.ts
electron/preload.ts
src/store/useStore.ts
src/utils/file.utils.ts

`File.path` is removed from version `32.0.0` of Electron, `webUtils.getPathForFile` should be used instead
- [v32.0.0 release note](https://github.com/electron/electron/releases/tag/v32.0.0)
- [Breaking change doc](https://github.com/electron/electron/blob/main/docs/breaking-changes.md#removed-filepath)

refactor: replace File.path with getPathForFile

---

.github/workflows/main.yml

Remove `master` and `feat/v2` from main GitHub workflow

ci: remove old branches

---

.github/workflows/build.yml
electron-builder.json5

**Context**
The application is crashing on Intel based Macs.
**Why**
- Before #254 the app was built without specifying any architecture
- This cause the app to be built for the os used in the [GitHub action](https://github.com/murgatt/recode-converter/blob/main/.github/workflows/build.yml#L13), at the time it was an Intel mac so the built app was for Intel Macs but it could be opened on Silicon Mac with Rosetta (very low performance)
- When `macos-latest` switched to a Silicon Mac, the built app was for Silicon Mac only
- After #254 there was a specified architecture `universal` to try to build for all Macs, but as we integrate ffmpeg that need to be downloaded for a specific architecture, the build was broken for Intel Macs
**Fix**
As we can't create a unique build for all Macs (or an …

fix: app crash on Intel Macs

---

.github/workflows/build.yml
.github/workflows/main.yml

In GitHub workflows:
- bump node version from `18` to `22`
- bump pnpm version from `9` to `10`

ci: bump node to 22 and pnpm to 10

---

src/components/FileImport.tsx

To due different child element drag event behavior on Windows, `dragLeave` was constantly triggered making the drop zone indicator flashing and prevent files to be dropped.
We now check if `dragLeave` is triggered from a child element before switching the state.
https://github.com/user-attachments/assets/9641fd65-4781-45bd-9736-302eac98f814

fix: file drag & drop on Windows

---

.prettierrc

Add `tailwindFunctions` option for `prettier-plugin-tailwindcss` to sort tailwind classes in `"clsx", "cn", "cx", "twMerge"` function calls
See [prettier-plugin-tailwindcss](https://github.com/tailwindlabs/prettier-plugin-tailwindcss?tab=readme-ov-file#sorting-classes-in-function-calls)

chore: add tailwindFunctions in prettier config

---

package.json

Approve ffmpeg & ffprobe installer deps for all platforms in pnpm `onlyBuiltDependencies` in the package.json to allow post install scripts to be run. For some reason, ffmpeg & ffprobe was sometimes not available causing conversion and metadata to fail
https://pnpm.io/fr/9.x/package_json#pnpmonlybuiltdependencies

build: approve ffmpeg & ffprobe installer

---

src/index.css

Check icon in file card was not green in dark mode.
This was caused by Tailwind v4 migration in #389 the success color [was not correctly migrated](https://github.com/murgatt/recode-converter/pull/389/files#diff-85da366246340e911d7a0eb9153e64137a1b31f0686c74d9aef9ae4f032cb09eL69) 
**Before**
**After**
- Set theme to dark
- Convert a file

fix: check icon color in dark theme
