package.json, public/conversionManager.js, src/registerElectronEvents.js, src/store/file/file.actions.js, yarn.lock
What I've done:
- added node-ffprobe
- get files info when one or multiple files are added
- add infos to file object 
N/A
=> feat: add node-ffprobe to get files info

public/conversionManager.js, public/ffmpeg.js, src/components/File/File.js, src/components/FileStreams/FileStreams.js, src/i18n/en.json, src/i18n/fr.json, src/registerElectronEvents.js, src/store/conversion/conversion.actions.js, src/store/file/file.actions.js
Uncheck streams to remove them from the output file
Launch the app, add a file to convert and display streams table.
Uncheck streams and start the conversion.
Unchecked streams should be removed from the output file.
=> feat(conversion): allow to remove specific streams from the output file

public/conversionManager.js, src/components/BitrateSelect/BitrateSelect.js, src/components/ChannelsSelect/ChannelsSelect.js, src/components/CodecSelect/CodecSelect.js, src/components/ConversionSettingsForm/ConversionSettingsForm.js, src/components/SampleRateSelect/SampleRateSelect.js, src/store/conversion/conversion.actions.js, src/store/conversionSettings/conversionSettings.actions.js, src/store/conversionSettings/conversionSettings.constants.js, src/store/conversionSettings/conversionSettings.reducer.js, src/store/file/file.actions.js, src/store/file/file.selectors.js, src/store/file/file.utils.js
Global improvements in the store:
- reusability of the selectors
- export util functions & constants in specific file
=> refactor(store): improve selectors & actions

public/ffmpeg.js
Conversion error when metadata contains space(s) due to `fluent-ffmpeg`.
[node-fluent-ffmpeg issue with workaround](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/issues/589)
The fix:
- metadata flag & value are now "two options" separated by a comma
- metadata are added with `.addOutputOptions` as multiple arguments instead of an array of options
Start the app, add a file and in the file streams tab, add a title with at least one space then run the conversion.
=> fix(conversion): conversion error when metadata with spaces

public/electron.js, public/ffmpeg.js, src/App.js, src/components/FfmpegAlert/FfmpegAlert.js, src/components/FfmpegAlert/index.js, src/i18n/en.json, src/i18n/fr.json, src/registerElectronEvents.js, src/store/reducers.js, src/store/ui/ui.actions.js, src/store/ui/ui.reducer.js, src/store/ui/ui.selectors.js
When the app start, check if FFMPEG is installed. If not display an alert.
=> feat: check if FFMPEG is installed

public/electron.js, src/App.js, src/components/VersionAlert/VersionAlert.js, src/components/VersionAlert/index.js, src/constants.js, src/i18n/en.json, src/i18n/fr.json, src/registerElectronEvents.js, src/store/ui/ui.actions.js, src/store/ui/ui.reducer.js, src/store/ui/ui.selectors.js, src/utils.js
=> feat: check for available update on start

src/App.js, src/Router.js, src/components/AppMenu/AppMenu.js, src/components/AppMenu/MenuItem.js, src/components/Player/Player.js, src/components/Player/index.js, src/config/featureFlip.js, src/featureFlipContext.js, src/i18n/en.json, src/i18n/fr.json, src/routes/ConverterPage.js, src/routes/VideoComparisonPage.js, src/routes/index.js
New module to compare two video side by side with a slider.
This module is in beta and is hidden for now.
This PR also introduce a feature flip system.
=> feat: [beta] video comparison slider

src/components/AppMenu/AppMenu.js, src/components/FfmpegAlert/FfmpegAlert.js, src/components/FileStreams/FileStreams.js, src/components/Snackbar/Snackbar.js, src/components/VersionAlert/VersionAlert.js, src/config/conversion/audio/bitrate.js, src/config/conversion/audio/channels.js, src/config/conversion/audio/codec.js, src/config/conversion/audio/samplerate.js, src/i18n/en.json, src/i18n/fr.json, src/modules/converter/AddFileFab/AddFileFab.js, src/modules/converter/BottomBar/BottomBar.js, src/modules/converter/ConversionDrawer/ConversionDrawer.js, src/modules/converter/DestinationInput/DestinationInput.js, src/modules/converter/File/File.js, src/modules/converter/FileList/FileList.js, src/routes/index.js, src/store/conversion/conversion.actions.js, src/store/file/file.actions.js
Refactor translation files to group translation keys by modules to have clearer lang files
App should run as usual without missing translation
=> refactor: lang files

src/modules/video-comparison/Player/Player.js
Add fullscreen button in player controls and improve controls styling.
The button allow to toggle the player fullscreen mode.
=> feat(player): [beta] add player fullscreen mode

.eslintignore, .eslintrc.cjs, .github/workflows/build.yml, .github/workflows/main.yml, .prettierignore, electron/foo.test.ts, package.json, prettier.config.js
Setup main CI running on:
- PR
- `main` / `master` branch
- `feat/v2` branch
=> ci(v2): setup main CI

package.json, pnpm-lock.yaml, src/App.tsx, src/components/AppMenu/AppMenu.tsx, src/components/AppMenu/AppMenuItem.tsx, src/components/AppMenu/index.ts, src/components/FileCard.tsx, src/components/FileList.tsx, src/components/ui/Card.tsx, src/components/ui/Form.tsx, src/components/ui/Label.tsx, src/components/ui/Select.tsx, src/hooks/useTheme.ts, src/i18n/locales/en.json, src/i18n/locales/fr.json, src/index.css, src/router.tsx, src/routes/Converter.tsx, src/routes/Settings.tsx, tailwind.config.js
- create routes
- add app menu
- main converter layout
- settings layout
- create `useTheme` hook to handle light/dark theme preference
- add UI components from shadcn (Card, Form, Label, Select)
=> feat(v2): main layout

package.json, pnpm-lock.yaml, src/components/FileList.tsx, src/components/__tests__/FileList.test.tsx
Animate file list (add/remove files) using [auto-animate](https://auto-animate.formkit.com/)
=> feat(v2): animate file list

electron/electron-env.d.ts, electron/preload.ts, src/components/FileImport.tsx, src/components/FileList.tsx, src/components/Footer/Footer.tsx, src/components/Footer/__tests__/Footer.test.tsx, src/components/__tests__/FileImport.test.tsx, src/components/__tests__/FileList.test.tsx, src/components/ui/Button.tsx, src/i18n/locales/en.json, src/i18n/locales/fr.json, src/routes/Converter.tsx
- display stop conversion button in the footer when conversion is running
- group store selectors inside `Converter.tsx` component and remove store selectors from child components by passing props instead
=> feat(v2): stop conversion

electron/ConversionManager.ts, electron/conversion-events.types.ts, electron/electron-env.d.ts, electron/get-metadata.ts, electron/preload.ts, package.json, pnpm-lock.yaml, schema/file.types.ts, src/hooks/useConversionEvents.ts, src/store/store.types.ts, src/store/useStore.ts
- add [@ffprobe-installer/ffprobe](https://www.npmjs.com/package/@ffprobe-installer/ffprobe) to get file metadata
- send back metadata and set it in video file object
=> feat(v2): get file metadata

src/components/SettingsForm/LanguageSelect.tsx, src/components/SettingsForm/NotificationsSelect.tsx, src/components/SettingsForm/SettingsForm.tsx, src/components/SettingsForm/ThemeSelect.tsx, src/components/SettingsForm/index.ts, src/hooks/useConversionEvents.ts, src/hooks/useSettingsForm.ts, src/hooks/useTheme.ts, src/i18n/index.ts, src/i18n/locales/en.json, src/i18n/locales/fr.json, src/routes/Settings.tsx, src/schema/settings.schema.ts, src/store/selectors.ts, src/store/store.types.ts, src/store/useStore.ts, src/utils/__tests__/settings.utils.test.ts, src/utils/index.ts, src/utils/settings.utils.ts
- add `SettingsForm` with `LanguageSelect`, `NotificationsSelect` & `ThemeSelect`
- save settings to local storage
- change language on `LanguageSelect` change
- switch theme on `ThemeSelect` change
- add `theme` to store and use it in `useTheme` to switch theme automatically
=> feat(v2): settings

src/components/SettingsForm/NotificationsSelect.tsx, src/hooks/useConversionEvents.ts, src/i18n/locales/en.json, src/i18n/locales/fr.json, src/utils/index.ts, src/utils/notifications.utils.ts
- ask notifications permission (if not alreay granted) on notifications setting change
- show notification when conversion (single file / all files) is complete according to notifications setting
=> feat(v2): notifications

schema/file.types.ts, src/components/FileCard/FileCard.tsx, src/components/FileCard/FileCardIcon.tsx, src/hooks/useConversionEvents.ts, src/store/store.types.ts, src/store/useStore.ts
- display file conversion error inside tooltip over error icon
- show error in client console
=> feat(v2): display conversion error

electron/convert/convert.utils.ts, schema/conversionSettings.schema.ts, src/components/ConversionSettingsForm/ConversionSettingsForm.tsx, src/components/ConversionSettingsForm/SubtitleSelect.tsx, src/i18n/locales/en.json, src/i18n/locales/fr.json, src/store/useStore.ts
- add new subtitle format select to conversion settings form
- add ffmpeg options to convert subtitles
=> feat(v2): subtitle conversion

electron/electron-env.d.ts, electron/electron.ts, electron/main.ts, electron/preload.ts, package.json, pnpm-lock.yaml, src/App.tsx, src/components/Footer/DestinationInput.tsx, src/components/UpdateAvailableModal.tsx, src/components/ui/AlertDialog.tsx, src/i18n/locales/en.json, src/i18n/locales/fr.json
- create UpdateAvailableModal displayed on application start if a new version is available
- fetch the latest release version with GitHub API and compare it to the current version (from package.json)
- add UI component: AlertDialog
- rename `dialog` window property to `electron`
=> feat(v2): update available modal

electron/ConversionManager.ts, electron/main.ts, package.json, pnpm-lock.yaml, src/components/FileCard/FileCard.tsx, src/components/Footer/DestinationInput.tsx, src/components/SettingsForm/FfmpegCommandSwitch.tsx, src/components/SettingsForm/LanguageSelect.tsx, src/components/SettingsForm/NotificationsSelect.tsx, src/components/SettingsForm/ThemeSelect.tsx, src/components/StreamTable/StreamTable.tsx, src/router.tsx, src/routes/Converter.tsx, src/utils/debounce.utils.ts, src/utils/index.ts
- setup analytics with Aptabse
- add debounce util function (to debounce event tracking when stream title change)
=> feat(v2): analytics with Aptabase

package.json, pnpm-lock.yaml
- bump `@testing-library/dom` from `9.3.3` to `9.3.4`
- bump `@testing-library/jest-dom` from `6.1.4` to `6.4.2`
- bump `@testing-library/react` from `14.1.0` to `14.2.1`
- bump `@testing-library/user-event` `14.5.1` to `14.5.2`
=> chore(deps): bump testing library

prettier.config.js, tsconfig.json
Duplicated prettier config file, remove useless one `prettier.config.js`
=> chore(prettier): remove useless duplicated prettier config file

package.json, pnpm-lock.yaml
=> fix(deps): bump electron from 28.2.1 to 29.1.0

package.json, pnpm-lock.yaml, src/components/FileImport.tsx
Remove react-dropzone and implement native file dropzone
=> refactor: remove react-dropzone

.github/dependabot.yml
=> chore: update dependabot.yml to group react & react-dom
